### ISSUE TITLE
create numbers disappear

### ISSUE THREAD

**Issue by om3ga6400** [vindocel/Dark-Mode-Everywhere-Fix#71]
without:
![image](https://github.com/vindocel/Dark-Everywhere/assets/98067930/e98e6a07-eb6f-4341-afb8-6ef129be641b)
with:
![image](https://github.com/vindocel/Dark-Everywhere/assets/98067930/3f1e501c-a7ba-4728-b038-a7771aa9fb26)
 more example:
 
 without:
![image](https://github.com/vindocel/Dark-Everywhere/assets/98067930/14555545-72bd-47f7-94c5-003fabbf0239)
with:
![image](https://github.com/vindocel/Dark-Everywhere/assets/98067930/4237e580-406f-4ab0-9ab4-3d073872bac7)

version 1.19.2

**Comment by om3ga6400** [comment]
@vindocel

**Comment by vindocel** [comment]
@OM3GA6400 This bug was already fixed in the texture for version 1.20, I'm not updating version 1.19 further, but to help you I made a Hotifix just for version 1.19 and I just released it here on Git on CurseForge, and on Modrinth

just download the file with hotifix name at the front
https://modrinth.com/resourcepack/dark-everywhere/version/cP0p5geN
https://legacy.curseforge.com/minecraft/texture-packs/dark-everywhere/files/5092539

**Comment by vindocel** [comment]
@OM3GA6400 test it and tell me if the problem has been fixed

**Comment by om3ga6400** [comment]
yaayyyy

**Comment by om3ga6400** [comment]
all fixed ty
